ChatApp/ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls",namespace='users')),
    path("chat/", include("chat.urls", namespace='chat')),
]

ChatApp/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path("", views.index, name="home"),
    path("index/", views.index, name="index"),
    path("room/", views.room, name="room"),  # Remove the room_name parameter
    path("direct_messages/", views.direct_messages, name="direct_messages"),
    path('invite/<str:room_name>/', views.invite_to_room, name='invite_to_room'),
    path('remove/<str:room_name>/', views.remove_room, name='remove_room'),
    path('remove/<str:room_name>/<str:username>/', views.remove_user_from_room, name='remove_user_from_room'),
    # Optional catch-all
    path("<str:any_path>", views.handle_unknown_url, name="catch-all"), 
]

ChatApp/users/urls.py
# users/urls.py

from django.contrib import admin
from . import views
from django.urls import path, include, re_path

app_name = 'users'

urlpatterns = [
    path("", views.dashboard, name="home"), #empty path https:/127.0.0.1:8000
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path('search/', views.search_users, name='search_users'),

    # Optional catch-all
    path("<str:any_path>", views.handle_unknown_url, name="catch-all"), 
]

ChatApp/users/models.py
# users/forms.py

from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    USER_TYPE = (
        ('basic', 'Basic User'),
        ('pro', 'Pro User'),
    )

    user_type = models.CharField(max_length=10, choices=USER_TYPE, default='basic')

ChatApp/users/forms.py
# users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'user_type')

ChatApp/users/views.py
# users/views.py

from django.contrib.auth import login
from users.models import User  
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import CustomUserCreationForm

def dashboard(request):
    return render(request, "users/dashboard.html")

def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("users:dashboard"))
        else:
            return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )

def search_users(request):
    query = request.GET.get('query')
    if query:
        # Filter users based on username (case-insensitive) excluding the logged-in user
        users = User.objects.filter(username__icontains=query).exclude(username=request.user.username)
    else:
        users = []  # Empty list if no query
    context = {'users': users, 'query': query}
    return render(request, 'users/search_users.html', context)

def handle_unknown_url(request, any_path):
    return redirect('users:dashboard')

ChatApp/users/templates/users/dashboard.html
<!-- ChatApp/chat/dashboard.html -->
{% extends 'base.html' %}
{% block content %}
<br>
Hello, <b>{{ user.username|capfirst|default:'Guest' }}!</b>
{% if user.is_authenticated %}
    {% if user.user_type == 'pro' %}
        (Pro)<sup>*</sup>
    {% else %}
        (Basic)<sup>*</sup>
    {% endif %}
    <br>
    <span style="color: #999; font-size: 0.8em;"><sup>*</sup>Pro users can create groups and add users, in addition to seeing entire chat history.</span>
{% endif %}

<div>
  <p></p>
  {% if user.is_authenticated %}
    <a href="{% url 'chat:index' %}">Groups</a><br>
    <a href="{% url 'users:search_users' %}">Search Users</a><br>
    <a href="{% url 'users:password_change' %}">Change password</a> <br>
    <a href="#" onclick="logout()">Logout</a>
  {% else %}
    <a href="{% url 'users:login' %}">Login</a>&nbsp;
    <a href="{% url 'users:register' %}">Register</a>
  {% endif %}
</div>

<script>
function logout() {
    // Create a form element
    var form = document.createElement('form');
    form.method = 'POST';
    form.action = '{% url "users:logout" %}';

    // Create a hidden input field for the CSRF token
    var csrfTokenInput = document.createElement('input');
    csrfTokenInput.type = 'hidden';
    csrfTokenInput.name = 'csrfmiddlewaretoken';
    csrfTokenInput.value = '{{ csrf_token }}';

    // Append the CSRF token input to the form
    form.appendChild(csrfTokenInput);

    // Append the form to the document body
    document.body.appendChild(form);

    // Submit the form
    form.submit();
}
</script>
{% endblock %}

ChatApp/users/templates/users/register.html
<!--users/templates/users/register.html-->

{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register">
</form>

<br><br>
<a href="{% url 'users:dashboard' %}">Dashboard</a>

{% endblock %}

ChatApp/users/templates/users/search_users.html
{% extends 'base.html' %}
{% block content %}
<br>
<h5>Hello, {{ user.username|capfirst|default:'Guest' }}!</h5>

<div>
  {% if user.is_authenticated %}
    <br>
    <h5>Search Users</h5>
    <form method="get">
      <label for="query">Enter the first few characters of username:</label><br>
      <input type="text" name="query" id="query" placeholder="User name" value="{{ query|default:'' }}" onfocus="clearQuery()">
      <input type="submit" value="Search">
    </form>
    <br>
    {% if users %}
      <h5>Search Results</h5>
      <ul>
        {% for user in users %}
          {% if not user.is_staff %}  <li>
            <a href="{% url 'chat:direct_messages' %}?receiver={{ user.username }}">{{ user.username|capfirst }}</a>
          </li>
          {% endif %}
        {% endfor %}
      </ul>
    {% else %}
      <p>No users found for your search.</p>
    {% endif %}
    <a href="#" onclick="logout()">Logout</a> &nbsp;
    <a href="{% url 'users:dashboard' %}">Dashboard</a> &nbsp;

  {% else %}
    <a href="{% url 'users:login' %}">Login</a>&nbsp;
    <a href="{% url 'users:register' %}">Register</a>
  {% endif %}
</div>

<script>
function clearQuery() {
    const queryInput = document.getElementById('query');
    if (queryInput.value === "None") {
        queryInput.value = '';
    }
}

function logout() {
    // Create a form element
    var form = document.createElement('form');
    form.method = 'POST';
    form.action = '{% url "users:logout" %}';

    // Create a hidden input field for the CSRF token
    var csrfTokenInput = document.createElement('input');
    csrfTokenInput.type = 'hidden';
    csrfTokenInput.name = 'csrfmiddlewaretoken';
    csrfTokenInput.value = '{{ csrf_token }}';

    // Append the CSRF token input to the form
    form.appendChild(csrfTokenInput);

    // Append the form to the document body
    document.body.appendChild(form);

    // Submit the form
    form.submit();
}
</script>
{% endblock %}